services:
  db:
    env_file: '.env'
    image: postgres:16-alpine
    shm_size: 512mb
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - main

  backend:
    env_file: '.env'  # pass variables to node.js
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
      target: prod
    volumes:
      - ./backend:/home/app
      - ./shared:/home/shared
      - /home/app/node_modules
      - /home/app/dist
    ports:
      - 3000:3000
    networks:
      - main
    depends_on:
      - db

  frontend:
    env_file: '.env'  # pass variables to node.js
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
      target: prod
    volumes:
      - ./frontend:/home/app
      - ./shared:/home/shared
      - /home/app/node_modules
      - /home/app/dist
    ports:
      - 8080:80
    networks:
      - main
    depends_on:
      - backend

volumes:
  db_data:

networks:
  main: