services:
  db:
    env_file: '.env'
    image: postgres:16-alpine
    shm_size: 512mb
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - main

  backend:
    env_file: '.env'  # pass variables to node.js
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    volumes:
      - ./backend:/home/app
      - ./shared:/home/shared
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - main
    depends_on:
      - db

  frontend:
    env_file: '.env'  # pass variables to node.js
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
    volumes:
      - ./frontend:/home/app
      - ./shared:/home/shared
    ports:
      - 5173:5173
    networks:
      - main
    depends_on:
      - backend
    command: npx vite preview --host 0.0.0.0 --port 5173

volumes:
  db_data:

networks:
  main: