services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '22:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - main

  db:
    env_file: '.env'
    image: postgres:16-alpine
    shm_size: 512mb
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - main

  backend:
    env_file: '.env'  # pass variables to node.js
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
      target: dev
    volumes:
      - ./shared:/home/shared
      - ./backend:/home/app
      - /home/app/node_modules
    ports:
      - ${BACKEND_PORT}:3000
    networks:
      - main
    depends_on:
      - db
    command: npx nest start --watch --sourceRoot=src --entryFile=app/src/main.js

  frontend:
    env_file: '.env'  # pass variables to node.js
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
      target: dev
    volumes:
      - ./frontend:/home/app
      - ./shared:/home/shared
      - /home/app/node_modules
    ports:
      - ${FRONTEND_PORT}:5173
    networks:
      - main
    depends_on:
      - backend
    command: npx vite --host 0.0.0.0 --port 5173

volumes:
  db_data:

networks:
  main: